<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <?php include_once "template/head.phtml" ?>
  <body>
    <div class="grid-container">
    <?php include_once "template/izbornik.phtml" ?>
    <div class="callout">
      <?php
		echo $content;
		?>
        </div>
        <?php include_once "template/footer.phtml" ?>
    </div>

    <?php include_once "template/skripte.phtml" ?>
  </body>
</html>
