/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Polaznik
 */
public class Prozor extends javax.swing.JFrame {

    /**
     * Creates new form Prozor
     */
    public Prozor() {
        initComponents();
        BazaTest baza= new BazaTest();
        baza.getVeza();
        DefaultTableModel tableModel=new DefaultTableModel();
        String[] colNames = {"Šifra","Naziv","Trajanje","Cijena"};
        
        try {
            PreparedStatement izraz=baza.veza.prepareStatement("select * from smjer");
            ResultSet rs=izraz.executeQuery();
            while (Table_Smjer.getRowCount()>0){
                for(int i=0;i<colNames.length;i++){

                TableColumn tc = Table_Smjer.getColumnModel().getColumn(i);
                tc.setHeaderValue(colNames[i]);}
                ((DefaultTableModel) Table_Smjer.getModel()).removeRow(0);     
            }
            int columns = rs.getMetaData().getColumnCount();
            while(rs.next())
        {  
            Object[] row = new Object[columns];
            for (int i = 1; i <= columns; i++)
            {  
                row[i - 1] = rs.getObject(i);
            }
            ((DefaultTableModel) Table_Smjer.getModel()).insertRow(rs.getRow()-1,row);
        }
            
        } catch (SQLException ex) {
            Logger.getLogger(Prozor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        btnHello.setText("Reci HELLO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnHello = new javax.swing.JButton();
        lblPoruka = new javax.swing.JLabel();
        btnOcisti = new javax.swing.JButton();
        btnPromjeniBoju = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Smjer = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHello.setText("ClickMe");
        btnHello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelloActionPerformed(evt);
            }
        });

        lblPoruka.setText("jLabel1");

        btnOcisti.setText("Ocisti");
        btnOcisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcistiActionPerformed(evt);
            }
        });

        btnPromjeniBoju.setText("Promjeni Boju");
        btnPromjeniBoju.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPromjeniBojuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPromjeniBojuMouseExited(evt);
            }
        });
        btnPromjeniBoju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniBojuActionPerformed(evt);
            }
        });

        Table_Smjer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Table_Smjer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPoruka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHello))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPromjeniBoju, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnOcisti, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPoruka)
                    .addComponent(btnHello))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnOcisti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPromjeniBoju)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelloActionPerformed
        System.out.println("Hello");
        lblPoruka.setText(JOptionPane.showInputDialog("Unesi ime"));
        
    }//GEN-LAST:event_btnHelloActionPerformed

    private void btnOcistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcistiActionPerformed
        lblPoruka.setText("");
    }//GEN-LAST:event_btnOcistiActionPerformed

    private void btnPromjeniBojuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniBojuActionPerformed
        lblPoruka.setForeground(Color.RED);
    }//GEN-LAST:event_btnPromjeniBojuActionPerformed

    private void btnPromjeniBojuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPromjeniBojuMouseEntered
        btnPromjeniBoju.setForeground(Color.RED);
    }//GEN-LAST:event_btnPromjeniBojuMouseEntered

    private void btnPromjeniBojuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPromjeniBojuMouseExited
        btnPromjeniBoju.setForeground(Color.BLACK);
        btnPromjeniBoju.setBackground(new Color(255,0,255));
    }//GEN-LAST:event_btnPromjeniBojuMouseExited

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Smjer;
    private javax.swing.JButton btnHello;
    private javax.swing.JButton btnOcisti;
    private javax.swing.JButton btnPromjeniBoju;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPoruka;
    // End of variables declaration//GEN-END:variables
}
