/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Polaznik
 */
public class Prozor extends javax.swing.JFrame {

    /**
     * Creates new form Prozor
     */
    public Prozor() {
        initComponents();
        
        btnHello.setText("Reci HELLO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHello = new javax.swing.JButton();
        lblPoruka = new javax.swing.JLabel();
        btnOcisti = new javax.swing.JButton();
        btnPromjeniBoju = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHello.setText("ClickMe");
        btnHello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelloActionPerformed(evt);
            }
        });

        lblPoruka.setText("jLabel1");

        btnOcisti.setText("Ocisti");
        btnOcisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcistiActionPerformed(evt);
            }
        });

        btnPromjeniBoju.setText("Promjeni Boju");
        btnPromjeniBoju.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPromjeniBojuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPromjeniBojuMouseExited(evt);
            }
        });
        btnPromjeniBoju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniBojuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPromjeniBoju))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOcisti))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblPoruka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                        .addComponent(btnHello)))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPoruka)
                    .addComponent(btnHello))
                .addGap(18, 18, 18)
                .addComponent(btnOcisti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPromjeniBoju)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelloActionPerformed
        System.out.println("Hello");
        lblPoruka.setText(JOptionPane.showInputDialog("Unesi ime"));
        
    }//GEN-LAST:event_btnHelloActionPerformed

    private void btnOcistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcistiActionPerformed
        lblPoruka.setText("");
    }//GEN-LAST:event_btnOcistiActionPerformed

    private void btnPromjeniBojuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniBojuActionPerformed
        lblPoruka.setForeground(Color.RED);
    }//GEN-LAST:event_btnPromjeniBojuActionPerformed

    private void btnPromjeniBojuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPromjeniBojuMouseEntered
        btnPromjeniBoju.setForeground(Color.RED);
    }//GEN-LAST:event_btnPromjeniBojuMouseEntered

    private void btnPromjeniBojuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPromjeniBojuMouseExited
        btnPromjeniBoju.setForeground(Color.BLACK);
        btnPromjeniBoju.setBackground(new Color(255,0,255));
    }//GEN-LAST:event_btnPromjeniBojuMouseExited

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHello;
    private javax.swing.JButton btnOcisti;
    private javax.swing.JButton btnPromjeniBoju;
    private javax.swing.JLabel lblPoruka;
    // End of variables declaration//GEN-END:variables
}
