/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.view;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Polaznik
 */
public class LjubavniKalkulatot extends javax.swing.JFrame {

    /**
     * Creates new form LjubavniKalkulatot
     */
    public LjubavniKalkulatot() {
        String ona;
        String on;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOn = new javax.swing.JTextField();
        txtOna = new javax.swing.JTextField();
        btnVoleSe = new javax.swing.JButton();
        lblPostotak = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPonovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ljubavni kalkulator");

        txtOna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOnaActionPerformed(evt);
            }
        });

        btnVoleSe.setText("Vole se ...");
        btnVoleSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoleSeActionPerformed(evt);
            }
        });

        lblPostotak.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblPostotak.setText("00%");

        jLabel1.setText("ONA:");

        jLabel2.setText("ON:");

        btnPonovo.setText("Ponovi");
        btnPonovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOna, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVoleSe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(btnPonovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPostotak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOna, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnVoleSe)
                .addGap(26, 26, 26)
                .addComponent(lblPostotak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnPonovo)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtOnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOnaActionPerformed

    private void btnVoleSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoleSeActionPerformed
        String  svaSlova= (txtOna.getText()+txtOn.getText()).toLowerCase();
                     
        //System.out.println(svaSlova);
        
        Map<Character,Integer> mapa = new HashMap<>();
        for (int i = 0; i < svaSlova.length(); i++) {
            char c = svaSlova.charAt(i);
            if (mapa.containsKey(c)) {
                int cnt = mapa.get(c);
                mapa.put(c, ++cnt);
            } else {
                mapa.put(c, 1);
            }
            }
        Collection <Integer> vrijednosti=mapa.values();
        Integer[] niz=vrijednosti.toArray(new Integer[vrijednosti.size()]);
        for(int v : niz){
            System.out.println(v);
        }
            
        
    }//GEN-LAST:event_btnVoleSeActionPerformed

    private void btnPonovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonovoActionPerformed
        txtOna.setText("");
        txtOn.setText("");
        lblPostotak.setText("00%");
    }//GEN-LAST:event_btnPonovoActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPonovo;
    private javax.swing.JButton btnVoleSe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPostotak;
    private javax.swing.JTextField txtOn;
    private javax.swing.JTextField txtOna;
    // End of variables declaration//GEN-END:variables
}
